version: '3'

tasks:
  build:
    cmds:
      - docker-compose -f docker/docker-compose.yml build --no-cache
  up:
    cmds:
      - docker-compose -f docker/docker-compose.yml up -d
  down:
    cmds:
      - docker-compose -f docker/docker-compose.yml down